on:
  push:
    branches:
      - master
  pull_request: {}
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  commits:
    name: Check commits format
    runs-on: ubuntu-latest
    steps:
      - name: Ensure commits are correctly named
        run: |
          echo "${{ fromJson(commits)[0].commit.message }}
