on:
  push:
    branches:
      - master
  pull_request: {}
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  commits:
    name: Check commits format
    runs-on: ubuntu-latest
    steps:
      - name: Ensure commits are correctly named
        run: |
          commits=$(curl -L -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "${{ github.event.pull_request._links.commits.href }}")
          echo "${{ fromJson('$commits')[0].commit.message }}
